### ISSUE TITLE
We should try to support`hthgu133pluspm`

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/identifier-refinery#2]
n/t

**Comment by Miserlou** [comment]
Likely http://bioconductor.org/packages/release/data/annotation/html/hthgu133pluspmprobe.html

**Comment by jaclyn-taroni** [comment]
Noted in person but recording here: We should currently have support for this platform. It is one of the two platforms that we implemented custom mappings for (see https://github.com/AlexsLemonade/refinebio/issues/329 and https://github.com/AlexsLemonade/identifier-refinery/blob/58ecb0e0b621d39c539a15dc4d772121e5a17901/R/custom_hthgu133pluspm.R).

**Comment by Miserlou** [comment]
Outputs for `hthgu133pluspm` and `htmg430a` were running, but we're being added to the final archive. Fix committed and new archive currently being updated to Zenodo.
