### ISSUE TITLE
Get Reserved DOI and Add `zenodo_url.txt` File

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/identifier-refinery#3]
See discussion here: https://github.com/AlexsLemonade/refinebio/pull/481#discussion_r207536713

**Comment by cgreene** [comment]
I don't think you need the reserved DOI as long as you're not generating the identifier refinery stuff as part of each deployment.

**Comment by Miserlou** [comment]
May not actually be necessary: https://github.com/AlexsLemonade/refinebio/pull/481#discussion_r207990349
