### ISSUE TITLE
Trouble extracting Affymetrix identifier refinery mappings 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/identifier-refinery#4]
I am looking into some Sentry errors related to the NOOP/gene conversion pipeline from the zebrafish crunch.

I have downloaded the files from this URL on both Ubuntu and Mac OSX: https://github.com/AlexsLemonade/refinebio/blob/221cd41685990ffd0308f61efeb28c4487374e18/workers/dockerfiles/Dockerfile.no_op#L45

And within the context of the Docker image `ccdlstaging/dr_no_op:latest` 

```
docker run -it ccdlstaging/dr_no_op bash
```

running `tar zxvf gene_indexes/zebrafish.tar.gz`, I get

```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
Have also tried this with `bovine.tar.gz`, `drosgenome1.tar.gz`, and `drosgenome1.tar.gz` with the same error.

**Comment by jaclyn-taroni** [comment]
Looks to me that the extension should be `.tsv.gz` -- can read it into R with `readr::read_tsv` no problem

**Comment by jaclyn-taroni** [comment]
Believe this is the problem: https://github.com/AlexsLemonade/identifier-refinery/blob/3dcb647ee9ab9386f17d1ed2ae7ab4e8c7f095d8/archive_outputs.py#L12

I'm running this locally now.

**Comment by Miserlou** [comment]
Yeah, I knew about this one but figured it wouldn't matter too much since it wouldn't ever be used directly. It'll take updating the published Zenodo package, as well as this: https://github.com/AlexsLemonade/refinebio/blob/675ea7a08757c60ea4aecf85a0f38b05714627a9/workers/data_refinery_workers/processors/no_op.py#L145

**Comment by jaclyn-taroni** [comment]
I'm not sure I agree with the notion that this wouldn't ever be used directly. If we didn't want folks to have the opportunity to use or inspect these directly, we would not necessarily put them on Zenodo. Thanks for the pointer in `no_op.py`.
